spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:14.2:///test
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: "schema_version"
